// import '@storybook/addon-console/register';
// import '@storybook/addon-backgrounds/register';
import '@storybook/addon-ondevice-actions/register';
import '@storybook/addon-ondevice-knobs/register';
// import 'storybook-addon-apollo-client/dist/register';
// import '@storybook/addon-a11y/register';
// import '@storybook/addon-jest/register';
// import '@storybook/addon-links/register';
// import '@storybook/addon-storysource/register';
// import '@storybook/addon-viewport/register';