export * from './content';
export * from './images';
export * from './files';
export * from './greatestCommonDivisor';
export * from './removeToken';
export * from './saveToken';
export * from './validPhoneNumber';
export function makeFriendlyUrl(text: any): string;
export function formatCreatedAt(createdAt: any): string;
export function arrayifyStyle(type: any): any[];
export function naiveFirstSentenceInText(text: any): any;
export function isValidHandle(handle: any): boolean;
export function parseCookie(str: any): any;
export function selectCookieStringFromContext(ctx: any): any;
export function selectTokenFromContext(ctx: any): any;
