export const LOCAL_IP: string;
export const API_PROTOCOL_DEV: 'http';
export const API_DOMAIN_DEV: string;
export const API_PORT_DEV: '4000';
export const API_ROUTE_DEV: 'graphql';
export const API_PROTOCOL_PROD: 'https';
export const API_DOMAIN_PROD: 'api.fora.co';
export const API_PORT_PROD: '80';
export const API_ROUTE_PROD: 'graphql';
export const API_PROTOCOL: 'http' | 'https';
export const API_DOMAIN: string;
export const API_PORT: '4000' | '80';
export const API_ROUTE: 'graphql';
export const API_URI_DEV: string;
export const API_URI_PROD: 'https://api.fora.co/graphql';
export const API_URI: string;
export const WS_API_URI_DEV: string;
export const WS_API_URI_PROD: 'wss://api.fora.co/graphql';
export const WS_API_URI: string;
