name: main

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    # strategy:
    #   matrix:
    #     node-version: [12.x, 14.x]
    steps:
      # this will check out the current branch (https://github.com/actions/checkout#Push-a-commit-using-the-built-in-token)
      - uses: actions/checkout@v2
      # installing Node
      - name: Use Node.js 12.x
        uses: actions/setup-node@v1
        with:
          # this will use the latest Node 12 version
          node-version: 12.x
          registry-url: 'https://registry.npmjs.org'
      # - name: Build on Node.js ${{ matrix.node-version }}
      #   uses: actions/setup-node@v1
      #   with:
      #     node-version: ${{ matrix.node-version }}
      - name: Install Dependencies
        run: yarn

      - name: Lint
        run: yarn lint
        id: lint

      - run: yarn build:babel
        name: Build Package

      - name: Unit Test
        run: yarn test:ci -u

      - name: Archive code coverage results
        uses: actions/upload-artifact@v2
        with:
          name: code-coverage-report
          path: ./coverage

      - name: Integration Test
        run: yarn test:integration

      - name: E2E Test
        run: yarn test:e2e

      - name: Set Git Config
        if: success() && github.ref == 'refs/heads/master'
        run: git config user.email "ryan@kanelabs.com" && git config user.name "Ryan Kane"

      - name: Tag Package Version
        if: success() && github.ref == 'refs/heads/master'
        run: yarn version --patch

      - name: Publish
        if: success() && github.ref == 'refs/heads/master'
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

  # test:
  #   runs-on: ubuntu-latest
  #   needs: build
  #   if: success()
  #   steps:
  #     - uses: actions/checkout@v2
  #     - name: Download Build Artifact from build job
  #       uses: actions/download-artifact@v2
  #       with:
  #         name: build-library
  #         path: ./lib
  #     - name: Unit Test
  #       run: yarn test:ci
  #     - name: Archive code coverage results
  #       uses: actions/upload-artifact@v2
  #       with:
  #         name: code-coverage-report
  #         path: /coverage
  #     - name: Integration Test
  #       run: yarn test:integration
  #     - name: E2E Test
  #       run: yarn test:e2e

  # deploy:
  #   runs-on: ubuntu-latest
  #   needs: test
  #   if: success() && github.ref == 'refs/heads/master'
  #   steps:
  #     - uses: actions/checkout@v2
  #     - name: Download Build Artifact from build job
  #       uses: actions/download-artifact@v2
  #       with:
  #         name: build-library
  #         path: /lib
  #     - name: Tag Package Version
  #       run: echo "how do i increment the package version?"
  #     - name: Publish
  #       run: yarn publish
